paths:
  train_data_dir: ../data
  outputs_dir: outputs
  model_path: model/mnist_cnn.pth
  test_data_dir: null

train:
  batch_size: 512
  epochs: 20
  log_interval: 30
  seed: 1

test:
  use_mnist: false
  num_samples: 10

optimizer:
  name: adam
  learning_rate: 0.001
